theme = "adwaita-dark"

[editor]
auto-format = false
continue-comments = false
auto-save.focus-lost = true
completion-timeout = 0
completion-trigger-len = 1
color-modes = true
end-of-line-diagnostics = "hint"
